### obtener todas los hamburguesas
GET http://localhost:3000/api/hamburguesas

### obtener una unica hamburguesa
GET http://localhost:3000/api/hamburguesas/2

### crear una hamburguesa
POST http://localhost:3000/api/hamburguesas
Content-Type: application/json

{
    "nombre": "TRIPLE QUESO",
    "descripcion": "MUCHO QUESO"
}
### modificar una hamburguesa
PUT http://localhost:3000/api/hamburguesas/12
Content-Type: application/json

{
    "nombre": "ROUTE 66",
    "descripcion": "HAMBUR HAMBUR"
}

### modificar una hamburguesa con patch
PATCH http://localhost:3000/api/hamburguesas/11
Content-Type: application/json

{
    "nombre": "ROUTE 66",
    "descripcion": "HAMBUR HAMBUR"
}

### borrar una hamburguesa
DELETE http://localhost:3000/api/hamburguesas/12