version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: basedatos
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
