### obtener todas los ingredientes
GET http://localhost:3000/api/ingredientes


### obtener un unico ingrediente
GET http://localhost:3000/api/ingredientes/1


### crear un ingrediente
POST http://localhost:3000/api/ingredientes
Content-Type: application/json

{
    "codIngrediente": "2",
    "descripcion": "dsasasd",
    "stock": 4
}

### modificar un ingrediente
PUT http://localhost:3000/api/ingredientes/1
Content-Type: application/json

{
    "codIngrediente": "3",
    "descripcion": "ffdddgs",
    "stock": 5
}

###modificar un ingrediente con patch
PATCH http://localhost:3000/api/ingredientes/4
Content-Type: application/json
{
    "codIngrediente": "4",
    "descripcion": "asassadsads",
    "stock": 6
}

### borrar un ingrediente
DELETE http://localhost:3000/api/ingredientes/2