### obtener todas los ingredientes
GET http://localhost:3000/api/ingredientes


### obtener un unico ingrediente
GET http://localhost:3000/api/ingredientes/2


### crear un ingrediente
POST http://localhost:3000/api/ingredientes
Content-Type: application/json

{
    "descripcion": "MAYONESA",
    "stock": 4
}

### modificar un ingrediente
PUT http://localhost:3000/api/ingredientes/2
Content-Type: application/json

{
    "descripcion": "Queso",
    "stock": 5
}

### modificar un ingrediente con patch
PATCH http://localhost:3000/api/ingredientes/4
Content-Type: application/json

{
    "descripcion": "Berenjena",
    "stock": 6
}

### borrar un ingrediente
DELETE http://localhost:3000/api/ingredientes/15