### obtener todos los clientes

GET http://localhost:3000/api/clientes

### obtener un unico cliente
GET http://localhost:3000/api/clientes/1

### dar de alta un cliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "REN",
    "apellido": "costa",
    "direccion": "abc 1244",
    "telefono": "341323213"
}
### modificar un cliente
PUT http://localhost:3000/api/clientes/1
Content-Type: application/json

{
    "nombre": "REN",
    "apellido": "asd",
    "direccion": "fgh",
    "telefono": ""
}

###modificar un cliente con patch
PATCH http://localhost:3000/api/clientes/UNO
Content-Type: application/json

    {    
        "idCliente": "ssa",
        "nombre": "REN",
        "apellido": "asd",
        "direccion": "fgh",
        "telefono": ""
    }
### borrar un cliente
DELETE http://localhost:3000/api/clientes/3
